- name: create temporary file
  tempfile:
    state: file
    suffix: .json
  register: __gcloud_temp_key
  changed_when: false

- name: adds service account key
  template:
    src: servicekey.json.j2
    dest: "{{ __gcloud_temp_key.path }}"
  changed_when: false

- name: activate service account
  shell: "CLOUDSDK_PYTHON_SITEPACKAGES=1 gcloud auth activate-service-account {{ gcloud_service_email }} --key-file {{ __gcloud_temp_key.path }}"
  changed_when: false

- name: sets default project
  command: gcloud config set core/project {{ gcloud_project_id }}
  changed_when: false

- name: remove gcloud tempfile
  file:
    path: "{{ __gcloud_temp_key.path }}"
    state: absent
  changed_when: false
